[package]
name = "swarm-discovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
dns-parser = "0.8.0"
hickory-proto = "0.24.0"
rand = "0.8.5"
socket2 = { version = "0.5.5", features = ["all"] }
tokio = { version = "1.35.1", features = ["macros", "net", "rt", "time"] }
tracing = "0.1.40"

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
